//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 10:35:43 AM EEST 
//


package org.opennms.ocs.inventory.client.response.snmp;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SNMP_DEVICE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SNMP">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CHECKSUM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CONTACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DOMAIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="IPADDR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LASTDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="LOCATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MACADDR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SNMPDEVICEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UPTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SNMP_FANS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MANUFACTURER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="REFERENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="REVISION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SERIALNUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author <A HREF="mailto:sergey.ovsyuk@gmail.com">Sergey Ovsyuk </A>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "m_snmpdevice"
})
@XmlRootElement(name = "SNMP_DEVICES")
public class SnmpDevices {

    @XmlElement(name = "SNMP_DEVICE", required = true)
    protected List<SnmpDevice> m_snmpdevice;

    /**
     * Gets the value of the m_snmpdevice property.
     * 
     * @return
     *     possible object is
     *   
     *     
     */
    public List<SnmpDevice> getSNMPDevices() {
    	if(m_snmpdevice == null){
    		m_snmpdevice = new ArrayList<SnmpDevice>();	
    	}
        return m_snmpdevice;
    }

    /**
     * Sets the value of the m_snmpdevice property.
     * 
     * @param value
     *     allowed object is
     *   
     *     
     */
    public void setSNMPDevices(List<SnmpDevice> value) {
        this.m_snmpdevice = value;
    }

	@Override
	public String toString() {
		return "SnmpDevices [m_snmpdevice=" + m_snmpdevice + "]";
	}


    

}
